# -*- coding: utf-8 -*-
"""Copy of Qwen_English_Hindi_LoRA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12vmChcql1vAxBNZXeEt9_y39r-BMY8Kn
"""

!pip install -q unsloth
!pip install -q transformers datasets accelerate peft trl bitsandbytes
!pip install -q evaluate sacrebleu rouge-score bert-score sentencepiece

import unsloth
import torch

import transformers
import datasets


print("All imports successful!")
print(torch.cuda.get_device_name(0))

from unsloth import FastLanguageModel

print("Unsloth ready!")

from datasets import load_dataset
dataset=load_dataset("cfilt/iitb-english-hindi")
print(dataset)

print(dataset["train"][0])

dataset=dataset["train"].shuffle(seed=42)

train_dataset=dataset.select(range(5000))
val_dataset=dataset.select(range(5000,5500))

def filter_empty(example):
    en = example["translation"]["en"]
    hi = example["translation"]["hi"]

    return (
        en is not None and hi is not None and
        len(en.strip()) > 0 and
        len(hi.strip()) > 0
    )

train_dataset = train_dataset.filter(filter_empty)
val_dataset = val_dataset.filter(filter_empty)

def format_prompt(example):

    en = example["translation"]["en"]
    hi = example["translation"]["hi"]

    messages = [
        {
            "role": "user",
            "content": f"Translate the following English sentence to Hindi:\n{en}"
        },
        {
            "role": "assistant",
            "content": hi
        }
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize = False,
        add_generation_prompt = False
    )

    return {"text": text}

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "Qwen/Qwen2.5-1.5B-Instruct",
    max_seq_length = 256,
    dtype = None,
    load_in_4bit = True,
    trust_remote_code = True,
)

train_dataset = train_dataset.map(format_prompt,batched=False)
val_dataset = val_dataset.map(format_prompt,batched=False)

def filter_long_examples(example):
    return len(tokenizer(example["text"])["input_ids"]) <= 256

train_dataset = train_dataset.filter(filter_long_examples)
val_dataset = val_dataset.filter(filter_long_examples)

print(len(train_dataset))
print(len(val_dataset))
print(train_dataset[0]["text"])

tokenizer.pad_token = tokenizer.eos_token
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = [
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
    lora_alpha = 16,
    lora_dropout = 0.1,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 42,
)
model.print_trainable_parameters()

FastLanguageModel.for_training(model)
from trl import SFTTrainer
from transformers import TrainingArguments

from transformers import TrainingArguments, EarlyStoppingCallback

training_args = TrainingArguments(

    output_dir = "outputs",


    per_device_train_batch_size = 2,
    gradient_accumulation_steps = 4,


    num_train_epochs = 10,


    learning_rate = 2e-4,
    lr_scheduler_type = "linear",


    fp16 = not torch.cuda.is_bf16_supported(),
    bf16 = torch.cuda.is_bf16_supported(),


    optim = "adamw_8bit",


    weight_decay = 0.01,


    logging_steps = 10,
    logging_dir = "./logs",
    report_to = "tensorboard",


    eval_strategy = "epoch",


    save_strategy = "epoch",
    save_total_limit = 2,


    load_best_model_at_end = True,
    metric_for_best_model = "eval_loss",
    greater_is_better = False,


    seed = 42,
)

trainer = SFTTrainer(

    model = model,
    tokenizer = tokenizer,

    train_dataset = train_dataset,
    eval_dataset = val_dataset,

    dataset_text_field = "text",

    max_seq_length = 256,

    packing = True,

    dataset_num_proc = 2,

    args = training_args,

    callbacks = [
        EarlyStoppingCallback(
            early_stopping_patience = 2
        )
    ],
)

print("Trainer is ready!")

trainer_stats = trainer.train()

model.save_pretrained("qwen_lora_model")
tokenizer.save_pretrained("qwen_lora_model")

print("Model saved successfully!")

FastLanguageModel.for_inference(model)

messages = [
    {
        "role": "user",
        "content": "Translate the following English sentence to Hindi:\nHow are you?"
    }
]

text = tokenizer.apply_chat_template(
    messages,
    tokenize = False,
    add_generation_prompt = True
)

inputs = tokenizer(
    text,
    return_tensors = "pt"
).to("cuda")

outputs = model.generate(
    **inputs,
    max_new_tokens = 64,
    do_sample = False,
    eos_token_id = tokenizer.eos_token_id,
)

decoded = tokenizer.decode(
    outputs[0],
    skip_special_tokens = True
)

response = decoded[len(text):].strip()

print("\nGenerated Translation:\n")
print(response)

predictions = []
references = []
english_sentences = []

for example in val_dataset:

    en = example["translation"]["en"]
    hi = example["translation"]["hi"]

    messages = [
        {
            "role": "user",
            "content": f"Translate the following English sentence to Hindi:\n{en}"
        }
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize = False,
        add_generation_prompt = True
    )

    inputs = tokenizer(
        text,
        return_tensors = "pt"
    ).to("cuda")

    outputs = model.generate(
        **inputs,
        max_new_tokens = 128,
        do_sample = False,
        eos_token_id = tokenizer.eos_token_id,
    )

    decoded = tokenizer.decode(
        outputs[0],
        skip_special_tokens = True
    )

    prediction = decoded[len(text):].strip()

    english_sentences.append(en)
    references.append(hi)
    predictions.append(prediction)

print("Prediction generation complete!")

from evaluate import load


bleu = load("bleu")

bleu_score = bleu.compute(
    predictions = predictions,
    references = [[ref] for ref in references]
)


rouge = load("rouge")

rouge_score = rouge.compute(
    predictions = predictions,
    references = references
)


bertscore = load("bertscore")

bert_score = bertscore.compute(
    predictions = predictions,
    references = references,
    lang = "hi"
)



print("\nBLEU Score:")
print(bleu_score["bleu"])

print("\nROUGE Scores:")
print(rouge_score)

print("\nBERTScore F1 Average:")
print(sum(bert_score["f1"]) / len(bert_score["f1"]))

import pandas as pd

results_df = pd.DataFrame({
    "English": english_sentences,
    "Reference_Hindi": references,
    "Predicted_Hindi": predictions
})

results_df.to_csv(
    "translation_results.csv",
    index = False,
    encoding = "utf-8-sig"
)

print("\nCSV saved successfully!")

print("\nSample Outputs:\n")
print(results_df.head())