# -*- coding: utf-8 -*-
"""Qwen_English_Hindi_LoRA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CEGwphQkkCGtY_z2AKk_QEuR6p2IHQzX
"""

!pip install -q unsloth
!pip install -q transformers datasets accelerate peft trl bitsandbytes
!pip install -q evaluate sacrebleu rouge-score bert-score sentencepiece

import unsloth
import torch

import transformers
import datasets


print("All imports successful!")
print(torch.cuda.get_device_name(0))

from unsloth import FastLanguageModel

print("Unsloth ready!")

from datasets import load_dataset
dataset=load_dataset("cfilt/iitb-english-hindi")
print(dataset)

print(dataset["train"][0])

dataset=dataset["train"].shuffle(seed=42)

train_dataset=dataset.select(range(5000))
val_dataset=dataset.select(range(5000,5500))

def filter_empty(example):
    en = example["translation"]["en"]
    hi = example["translation"]["hi"]

    return (
        en is not None and hi is not None and
        len(en.strip()) > 0 and
        len(hi.strip()) > 0
    )

train_dataset = train_dataset.filter(filter_empty)
val_dataset = val_dataset.filter(filter_empty)

def format_prompt(example):
    en = example["translation"]["en"]
    hi = example["translation"]["hi"]

    text = f"""Translate English to Hindi:

English: {en}

Hindi: {hi}{tokenizer.eos_token}"""

    return {"text": text}

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "Qwen/Qwen2.5-1.5B-Instruct",
    max_seq_length = 256,
    dtype = None,
    load_in_4bit = True,
)

train_dataset = train_dataset.map(format_prompt)
val_dataset = val_dataset.map(format_prompt)

def filter_long_examples(example):
    return len(tokenizer(example["text"])["input_ids"]) <= 256

train_dataset = train_dataset.filter(filter_long_examples)
val_dataset = val_dataset.filter(filter_long_examples)

print(len(train_dataset))
print(len(val_dataset))
print(train_dataset[0]["text"])

tokenizer.pad_token = tokenizer.eos_token
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = [
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
    lora_alpha = 16,
    lora_dropout = 0.05,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 42,
)

FastLanguageModel.for_training(model)
from trl import SFTTrainer
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir = "outputs",


    per_device_train_batch_size = 2,
    gradient_accumulation_steps = 4,


    num_train_epochs = 1,


    learning_rate = 2e-4,


    fp16 = not torch.cuda.is_bf16_supported(),
    bf16 = torch.cuda.is_bf16_supported(),


    logging_steps = 10,

    optim = "adamw_8bit",


    weight_decay = 0.01,


    lr_scheduler_type = "linear",


    seed = 42,


    save_strategy = "epoch",


    report_to = "none",
)

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,

    train_dataset = train_dataset,
    eval_dataset = val_dataset,

    dataset_text_field = "text",

    max_seq_length = 256,

    args = training_args,
)

print("Trainer is ready!")

trainer_stats = trainer.train()

model.save_pretrained("qwen_lora_model")
tokenizer.save_pretrained("qwen_lora_model")

print("Model saved successfully!")
FastLanguageModel.for_inference(model)

prompt = """Translate English to Hindi:

English: How are you?

Hindi:"""

inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

outputs = model.generate(
    **inputs,
    max_new_tokens = 64,
    temperature = 0.2,
)

response = tokenizer.decode(outputs[0], skip_special_tokens=True)

print(response)

predictions = []
references = []
english_sentences = []

for example in val_dataset:

    en = example["translation"]["en"]
    hi = example["translation"]["hi"]

    prompt = f"""Translate English to Hindi:

English: {en}

Hindi:"""

    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    outputs = model.generate(
        **inputs,
        max_new_tokens = 128,
        do_sample = False,
        temperature = 0.0,
        eos_token_id = tokenizer.eos_token_id,
    )

    decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)

    prediction = decoded.split("Hindi:")[-1].strip()

    english_sentences.append(en)
    references.append(hi)
    predictions.append(prediction)

print("Prediction generation complete!")

from evaluate import load


bleu = load("bleu")
bleu_score = bleu.compute(
    predictions=predictions,
    references=[[ref] for ref in references]
)


rouge = load("rouge")
rouge_score = rouge.compute(
    predictions=predictions,
    references=references
)


bertscore = load("bertscore")
bert_score = bertscore.compute(
    predictions=predictions,
    references=references,
    lang="hi"
)

print("BLEU Score:", bleu_score["bleu"])

print("\nROUGE Scores:")
print(rouge_score)

print("\nBERTScore F1 Average:")
print(sum(bert_score["f1"]) / len(bert_score["f1"]))

import pandas as pd

results_df = pd.DataFrame({
    "English": english_sentences,
    "Reference_Hindi": references,
    "Predicted_Hindi": predictions
})

results_df.to_csv("translation_results.csv", index=False,encoding="utf-8-sig")

print(results_df.head())

print("\nCSV saved successfully!")